### ISSUE TITLE
Validação de data

### ISSUE THREAD

**Issue by giulianon** [dliocode/datavalidator#6]
Boa tarde Danilo. Primeiramente parabéns pelo projeto. Baita mão na roda pra validação, principalmente em APIs.

Danilo, estou validando um campo data de um JSON que permite null da seguinte forma:
```
.Validate('data_ultima_visita')
          .Value
            .IsOptional
            .IsLength(10,10).WithMessage('Campo data_ultima_visita deve ter tamanho 10')
            .IsDate(false).WithMessage('Campo data_ultima_visita é uma data inválida')
          .&End
        .&End
```
        
Se eu envio dessa forma a validação funciona perfeitamente
{ "data_ultima_visita": null}

Mas se eu envio dessa forma a validação falha
{ "data_ultima_visita": ""}

Eu segui o exemplo, então queria saber se eu estou fazendo algo errado o se é algum bug mesmo.

**Comment by dliocode** [comment]
Você quer considerar o vazio { "data_ultima_visita": ""} como válido?

**Comment by giulianon** [comment]
Na verdade como o campo é opcional, se vier null tudo ok. 
Se vier um valor diferente de null ele tem que ser no tamanho de uma data e também uma data válida.
Quando vem "" ele não pega na validação do isLength e nem na validação da data.

**Comment by dliocode** [comment]
Entendi..

A opção "IsOptional" ela deve ser usada pra quando o valor vier nulo ou vazio - e você não quer que ele faça a validação.

A nova opção, vai te dar acesso ao valor do JSONValue, onde você vai dizer para o validador se deve ser opcional ou não.

Faz assim.. Eu vou gerar um release que vai ter uma opção pra ti fazer isso!

```
                .Validate('birthDate')
                  .Key
                    .IsRequired.WithMessage('Informe a key ${key}')
                  .&End

                  .Value
                    .Trim
                    .IsOptional(
                    function(const AValue: TJSONValue): Boolean
                    begin
                      Result := AValue.Null;
                    end)
                    .IsJSONString.WithMessage('${key} - ${value} - Não é do tipo string!')
                    .IsLength(10,10).WithMessage('${key} - Deve ter somente 10 caracteres!')
                    .IsDate(False).WithMessage('${key} - ${value} - Não é uma data válida!')
                    .&Not.IsDateGreaterThan(Now, False).WithMessage('${key} - ${value} - A data informada não pode ser maior que a data atual!')
                    .&Not.IsDateLessThan(IncYear(Now, -90), False).WithMessage('${key} - ${value} - A data informada não pode ser menor que %s', [FormatDateTime('yyyy-mm-dd', IncYear(Now, -90))])
                  .&End
                .&End
```

**Comment by dliocode** [comment]
@giulianon 
https://github.com/dliocode/datavalidator/releases/tag/2.0.2

**Comment by giulianon** [comment]
> 

Assim já resolve. Aproveitando eu consigo ter esse mesmo esquema ai pra ter um validador customizado tipo: 

.Validate('birthDate')
                  .Key
                    .IsRequired.WithMessage('Informe a key ${key}')
                  .&End

                  .Value
                    .Trim
                    .IsOptional(
                    function(const AValue: TJSONValue): Boolean
                    begin
                      Result := AValue.Null;
                    end)
                    .CustomValidator(
                    function(const AValue: TJSONValue): Boolean
                    begin
                      // Teste por exemplo se é menor de idade
                      Result := AValue.GetValue<Integer> < 18;
                    end)
                     )
                    .IsJSONString.WithMessage('${key} - ${value} - Não é do tipo string!')
                    .IsLength(10,10).WithMessage('${key} - Deve ter somente 10 caracteres!')
                    .IsDate(False).WithMessage('${key} - ${value} - Não é uma data válida!')
                    .&Not.IsDateGreaterThan(Now, False).WithMessage('${key} - ${value} - A data informada não pode ser maior que a data atual!')
                    .&Not.IsDateLessThan(IncYear(Now, -90), False).WithMessage('${key} - ${value} - A data informada não pode ser menor que %s', [FormatDateTime('yyyy-mm-dd', IncYear(Now, -90))])
                  .&End
                .&End

**Comment by dliocode** [comment]
Pode usar esse aqui!

```delphi
                    .CustomJSONValue(
                    function(const AValue: TJSONValue): Boolean
                    begin


                    end)
```

**Comment by dliocode** [comment]
Lembrando que você pode retornar mensagem personalizadas.

Ex: 1

``` delphi
                    .CustomJSONValue(
                    function(const AValue: TJSONValue): Boolean
                    begin


                    end)
``` 

Ex: 2

``` delphi
                    .CustomJSONValue(
                    function(const AValue: TJSONValue; var AMessage: string): Boolean
                    begin
                      Result := False;

                      if AValue.Null then
                      begin
                        AMessage := 'Valor é nulo';
                        Exit;
                      end;
                      
                      if not AValue is TJSONNumber then
                      begin
                        AMessage := 'Valor deve ser númerico';
                        Exit;
                      end;

                      if AValue.GetValue<Integer> < 18 then
                      begin
                        AMessage := 'Valor menor que 18';
                        Exit;
                      end;                      
                      
                      Result := True;
                    end)
```

**Comment by giulianon** [comment]
> Lembrando que você pode retornar mensagem personalizadas.
> 
> Ex: 1
> 
> ```pascal
>                     .CustomJSONValue(
>                     function(const AValue: TJSONValue): Boolean
>                     begin
> 
> 
>                     end)
> ```
> 
> Ex: 2
> 
> ```pascal
>                     .CustomJSONValue(
>                     function(const AValue: TJSONValue; var AMessage: string): Boolean
>                     begin
>                       Result := False;
> 
>                       if AValue.Null then
>                       begin
>                         AMessage := 'Valor é nulo';
>                         Exit;
>                       end;
>                       
>                       if not AValue is TJSONNumber then
>                       begin
>                         AMessage := 'Valor deve ser númerico';
>                         Exit;
>                       end;
> 
>                       if AValue.GetValue<Integer> < 18 then
>                       begin
>                         AMessage := 'Valor menor que 18';
>                         Exit;
>                       end;                      
>                       
>                       Result := True;
>                     end)
> ```

Perfeito.

Sem querer abusar, mais uma então. 

Tem alguma forma de e comparar 2 values de um TJSONObject?

Exemplo:

```
{
    "senha":"12345",
    "confirmacao_Senha":"123456"
}

.Validate('senha')
    .Value
        .IsEquals('confirmacao_senha').WithMessage('Senhas não conferem')
    .&End
.&End
```

Isso também encaixaria no .isDateBetween()

**Comment by giulianon** [comment]
{
    "data_inicio":"2022-01-11",
    "data_fim":"2022-01-10"
}

.Validate('dataInicio')
    .Value
        .IsDateGreaterThan('data_fim').WithMessage('Período inválido')
    .&End
.&End

**Comment by dliocode** [comment]
Eu faço assim hoje;

``` delphi
function TUsuarioValidator.AlterarSenha(const ABody: TJSONObject): IDataValidatorResult;
begin
    Result :=
      TDataValidator.JSON(ABody)
      .Validate('email')
        .Key
          .IsRequired.WithMessage('Faltou informar a key "${key}"')
        .&End

        .Value
          .AddSchema(SchemaEmail)
        .&End
      .&End

      .Validate('senha_atual')
        .Key
          .IsRequired.WithMessage('Faltou informar a key "${key}"')
        .&End

        .Value
          .Trim
          .&Not.IsEmpty.WithMessage('Informe a senha atual!')
          .IsLength(6, 30).WithMessage('Informe a senha atual de 6 à 30 caracteres!')
        .&End
      .&End

      .Validate('nova_senha')
        .Key
          .IsRequired.WithMessage('Faltou informar a key "${key}"')
        .&End

        .Value
          .Trim
          .&Not.IsEmpty.WithMessage('Informe a nova senha!')
          .IsLength(6, 30).WithMessage('Informe a nova senha de 6 à 30 caracteres!')
          .CustomValue(
          function(const AValue: string; var AMessage: string): Boolean
          var
            LSenhaAtual: string;
          begin
            LSenhaAtual := ABody.GetValue<string>('senha_atual');

            AMessage := 'A nova senha não pode ser igual a senha atual!';
            Result := not AValue.Equals(LSenhaAtual);

            if not Result then
              Exit;

            Result := not LUsuario.CheckPassword(AValue);
          end)
        .&End
      .&End

      .Check;
end;
```

**Comment by giulianon** [comment]
> Eu faço assim hoje;
> 
> ```pascal
> function TUsuarioValidator.AlterarSenha(const ABody: TJSONObject): IDataValidatorResult;
> begin
>     Result :=
>       TDataValidator.JSON(ABody)
>       .Validate('email')
>         .Key
>           .IsRequired.WithMessage('Faltou informar a key "${key}"')
>         .&End
> 
>         .Value
>           .AddSchema(SchemaEmail)
>         .&End
>       .&End
> 
>       .Validate('senha_atual')
>         .Key
>           .IsRequired.WithMessage('Faltou informar a key "${key}"')
>         .&End
> 
>         .Value
>           .Trim
>           .&Not.IsEmpty.WithMessage('Informe a senha atual!')
>           .IsLength(6, 30).WithMessage('Informe a senha atual de 6 à 30 caracteres!')
>         .&End
>       .&End
> 
>       .Validate('nova_senha')
>         .Key
>           .IsRequired.WithMessage('Faltou informar a key "${key}"')
>         .&End
> 
>         .Value
>           .Trim
>           .&Not.IsEmpty.WithMessage('Informe a nova senha!')
>           .IsLength(6, 30).WithMessage('Informe a nova senha de 6 à 30 caracteres!')
>           .CustomValue(
>           function(const AValue: string; var AMessage: string): Boolean
>           var
>             LSenhaAtual: string;
>           begin
>             LSenhaAtual := ABody.GetValue<string>('senha_atual');
> 
>             AMessage := 'A nova senha não pode ser igual a senha atual!';
>             Result := not AValue.Equals(LSenhaAtual);
> 
>             if not Result then
>               Exit;
> 
>             Result := not LUsuario.CheckPassword(AValue);
>           end)
>         .&End
>       .&End
> 
>       .Check;
> end;
> ```

Entendi. Dessa maneira eu vi que daria pra fazer, mas a dúvida era mais pra saber se ali dentro eu conseguia pegar o valor  através de alguma função anônima ou algo do tipo. 

Era isso Danilo. Muito obrigado pela atenção e mais uma vez parabéns pelo projeto.

**Comment by dliocode** [comment]
Obrigado!

Qualquer coisa só chamar!
